package com.youTransactor.uCube.api;

public enum UCubeAPIState {
    IDLE,
    CHECK_BT,
    CANCEL_ALL,
    CHECK_BT_PERMISSION,
    INIT_RPC_MANAGER,
    PAIR_DEVICE,
    REGISTER_DEVICE,
    RETRIEVE_DEVICE_INFOS,
    RETRIEVE_DEVICE_CERTIFICAT,
    RETRIEVE_DEVICE_CONFIG,
    CHECK_UPDATE,
    DOWNLOAD_BINARY,
    UPDATE_DEVICE,
    SEND_LOGS,
    RECONNECT
}
